### PR TITLE
Tag support

### PR DESCRIPTION
**Pull request by psquickitjayant**
Removed tracking pixel and added async XMLHttpRequest

### CODE REVIEW

**Comment by vhalbwachs** [comment]
If we use ajax instead of a tracking pixel, I think we're going to run into issues with CORS. Have you tested this on a site that isn't hosted on Loggly's domain?

**Comment by mostlyjason** [comment]
Yeah CORS headers are live now. I believe they tested but @psquickitjayant can confirm.

**Comment by psquickitjayant** [comment]
@vhalbwachs I have tested it with "content-type:text/plain" and working fine. sends message to loggly and the logs are parsed as JSON logs in Loggly dashboard.

send "content-type:application/json" throws the 405 dues to CORS but may be we can avoid it using `text/plain`

**Comment by mostlyjason** [comment]
@vhalbwachs reminder to merge when you are done reviewing

**Comment by psquickitjayant** [comment]
@mostlyjason  you will need to upload the latest scripts on cloudfront.

**Comment by selurvedu** [comment]
:+1:
@mostlyjason I'm waiting for an updated version on Cloudfront. Please update the script ASAP.

**Pull request merged**
