### PR TITLE
Add tags and browser information in log objects

### PR DESCRIPTION
**Pull request by nicomlas**

### CODE REVIEW

**Comment by myroslav** [comment]
It look like the features in this pull request are desperately needed. See #2

**Comment by mostlyjason** [comment]
Unfortunately tags aren't supported in our tracking pixel right now. We're working on an update to our collectors that will allow this but it might be a couple weeks before we can make it.

**Comment by selurvedu** [comment]
Hi,
"a couple of weeks" is today. :)
Is there any progress?

**Comment by nicomlas** [comment]
@mostlyjason : "tags aren't supported in our tracking pixel right now"

However, I used it for this PR and deployed it in production (www.tripndrive.com), It works perfectly.

**Comment by mostlyjason** [comment]
Should have better tag support in #25

**Comment by mostlyjason** [comment]
Closing since this is deprecated by #25. If there is additional browser info you want to add can you merge it with the new release and resubmit?

**Pull request closed without merging**
