### PR TITLE
Add commonjs / npm support

### LINKED ISSUE #30: Publish to npm
Hi there,

Is there any chance you could publish this to npm as well as bower? You'll just need to update your package.json file to add an extra field like so:
```
browser: "src/loggly.tracker.js",
```

Change the version to 2.3.0 to match what's on bower, and then run `npm publish`

Thanks!

### PR DESCRIPTION
**Pull request by mattlewis92**
Closes #30

### CODE REVIEW

**Comment by mattlewis92** [comment]
Great, thanks a lot!

**Comment by mattlewis92** [comment]
Any chance this could be published to npm as well please? (`npm publish` from the root of the repo) Thanks!

**Comment by mostlyjason** [comment]
@psquickitjayant can you do this?

**Comment by kpdecker** [comment]
I've published this under https://www.npmjs.com/package/loggly-jslogger since I needed this. Glad to transfer ownership to someone actually in the project as I'm not certain that I can maintain this, not being closely tied to the project.

**Pull request merged**
